# filters for nanopore bcftools calls
bcftools:
  filters:
    min_depth:       0
    min_fed:         0.2
    max_depth:       0
    min_qual:        85
    min_strand_bias: 1
    min_bqb:         0
    min_mqb:         0
    min_rpb:         0
    max_sgb:         0
    min_vdb:         0.00001
    min_mq:          0
    min_frs:         0.90
