name: tbpore
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "python>=3.8,<4.0"
  - mamba
  - just=0.10
  - ca-certificates
  - certifi
  - openssl
  - ripgrep
  - poetry=1.1
  - mykrobe=0.10
  - rasusa
  - samtools=1.13
  - gsl
  - bcftools=1.13